export const languages = [
  { name: 'English', code: 'en', category: "" },
  { name: 'Spanish - español', code: 'es', category: "" },
  { name: 'Chinese (Cantonese)', code: 'zh-ca', category: "" },
  { name: 'Chinese (Mandarin)', code: 'zh-ma', category: "" },
  { name: 'Filipino (Tagalog)', code: 'fil', category: "" },
  { name: 'Vietnamese - Tiếng Việt', code: 'vi', category: "" },
  { name: 'Arabic - العربية', code: 'ar', category: "" },
  { name: 'French - français', code: 'fr', category: "" },
  { name: 'Hebrew - עברית', code: 'he', category: "" },
  { name: 'Korean - 한국어', code: 'ko', category: "" },
  { name: 'Russian - русский', code: 'ru', category: "" },
  { name: 'Portuguese (Brazil)', code: 'pt-BR', category: "" },
  { name: 'German - deutsch', code: 'de', category: "" },
  { name: 'Japanese - 日本語', code: 'ja', category: "" },
  { name: 'Hindi - हिन्दी', code: 'hi', category: ""},
  { name: 'Italian - italiano', code: 'it', category: "" },
  { name: 'Afrikaans', code: 'af', category: "More" },
  { name: 'Albanian - shqip', code: 'sq', category: "More" },
  { name: 'Amharic - አማርኛ', code: 'am', category: "More" },
  { name: 'Aragonese - aragonés', code: 'an', category: "More" },
  { name: 'Armenian - հայերեն', code: 'hy', category: "More" },
  { name: 'Asturian - asturianu', code: 'ast', category: "More" },
  { name: 'Azerbaijani - azərbaycan dili', code: 'az', category: "More" },
  { name: 'Basque - euskara', code: 'eu', category: "More" },
  { name: 'Belarusian - беларуская', code: 'be', category: "More" },
  { name: 'Bengali - বাংলা', code: 'bn', category: "More" },
  { name: 'Bosnian - bosanski', code: 'bs', category: "More" },
  { name: 'Breton - brezhoneg', code: 'br', category: "More" },
  { name: 'Bulgarian - български', code: 'bg', category: "More" },
  { name: 'Catalan - català', code: 'ca', category: "More" },
  { name: 'Central Kurdish - کوردی (دەستنوسی عەرەبی)', code: 'ckb', category: "More" },
  { name: 'Corsican', code: 'co', category: "More" },
  { name: 'Croatian - hrvatski', code: 'hr', category: "More" },
  { name: 'Czech - čeština', code: 'cs', category: "More" },
  { name: 'Danish - dansk', code: 'da', category: "More" },
  { name: 'Dutch - Nederlands', code: 'nl', category: "More" },
  { name: 'Esperanto - esperanto', code: 'eo', category: "More"},
  { name: 'Estonian - eesti', code: 'et', category: "More" },
  { name: 'Ewe', code: 'ewe', category: "More" },
  { name: 'Faroese - føroyskt', code: 'fo', category: "More" },
  { name: 'Finnish - suomi', code: 'fi', category: "More" },
  { name: 'Galician - galego', code: 'gl', category: "More" },
  { name: 'Ga', code: 'ga', category: "More" },
  { name: 'Georgian - ქართული', code: 'ka', category: "More" },
  { name: 'Greek - Ελληνικά', code: 'el', category: "More" },
  { name: 'Guarani', code: 'gn', category: "More" },
  { name: 'Gujarati - ગુજરાતી', code: 'gu', category: "More" },
  { name: 'Hausa', code: 'ha', category: "More" },
  { name: 'Hawaiian - ʻŌlelo Hawaiʻi', code: 'haw', category: "More" },
  { name: 'Hungarian - magyar', code: 'hu', category: "More" },
  { name: 'Icelandic - íslenska', code: 'is', category: "More" },
  { name: 'Indonesian - Indonesia', code: 'id', category: "More" },
  { name: 'Interlingua', code: 'ia', category: "More" },
  { name: 'Irish - Gaeilge', code: 'ir', category: "More" },
  { name: 'Kannada - ಕನ್ನಡ', code: 'kn', category: "More" },
  { name: 'Kazakh - қазақ тілі', code: 'kk', category: "More" },
  { name: 'Khmer - ខ្មែរ', code: 'km', category: "More" },
  { name: 'Kurdish - Kurdî', code: 'ku', category: "More" },
  { name: 'Kyrgyz - кыргызча', code: 'ky', category: "More" },
  { name: 'Lao - ລາວ', code: 'lo', category: "More" },
  { name: 'Latin', code: 'la', category: "More" },
  { name: 'Latvian - latviešu', code: 'lv', category: "More" },
  { name: 'Lingala - lingála', code: 'ln', category: "More" },
  { name: 'Lithuanian - lietuvių', code: 'lt', category: "More" },
  { name: 'Macedonian - македонски', code: 'mk', category: "More" },
  { name: 'Malay - Bahasa Melayu', code: 'ms', category: "More" },
  { name: 'Malayalam - മലയാളം', code: 'ml', category: "More" },
  { name: 'Maltese - Malti', code: 'mt', category: "More" },
  { name: 'Marathi - मराठी', code: 'mr', category: "More" },
  { name: 'Mongolian - монгол', code: 'mn', category: "More" },
  { name: 'Nepali - नेपाली', code: 'ne', category: "More" },
  { name: 'Norwegian - norsk', code: 'no', category: "More" },
  { name: 'Occitan', code: 'oc', category: "More" },
  { name: 'Oriya - ଓଡ଼ିଆ', code: 'or', category: "More" },
  { name: 'Oromo - Oromoo', code: 'om', category: "More" },
  { name: 'Pashto - پښتو', code: 'ps', category: "More" },
  { name: 'Persian - فارسی', code: 'fa', category: "More" },
  { name: 'Polish - polski', code: 'pl', category: "More" },
  { name: 'Portuguese (Portugal) - português (Portugal)', code: 'pt-PT', category: "More" },
  { name: 'Punjabi - ਪੰਜਾਬੀ', code: 'pa', category: "More" },
  { name: 'Quechua', code: 'qu', category: "More" },
  { name: 'Romanian - română', code: 'ro', category: "More" },
  { name: 'Romansh - rumantsch', code: 'rm', category: "More" },
  { name: 'Scottish Gaelic', code: 'gd', category: "More" },
  { name: 'Serbian - српски', code: 'sr', category: "More" },
  { name: 'Serbo - Croatian', code: 'sh', category: "More" },
  { name: 'Shona - chiShona', code: 'sn', category: "More" },
  { name: 'Sindhi', code: 'sd', category: "More" },
  { name: 'Sinhala - සිංහල', code: 'si', category: "More" },
  { name: 'Slovak - slovenčina', code: 'sk', category: "More" },
  { name: 'Slovenian - slovenščina', code: 'sl', category: "More" },
  { name: 'Somali - Soomaali', code: 'so', category: "More" },
  { name: 'Southern Sotho', code: 'st', category: "More" },
  { name: 'Sundanese', code: 'su', category: "More" },
  { name: 'Swahili - Kiswahili', code: 'sw', category: "More" },
  { name: 'Swedish - svenska', code: 'sv', category: "More" },
  { name: 'Tajik - тоҷикӣ', code: 'tg', category: "More" },
  { name: 'Tamil - தமிழ்', code: 'ta', category: "More" },
  { name: 'Tatar', code: 'tt', category: "More" },
  { name: 'Telugu - తెలుగు', code: 'te', category: "More" },
  { name: 'Thai - ไทย', code: 'th', category: "More" },
  { name: 'Tigrinya - ትግርኛ', code: 'ti', category: "More" },
  { name: 'Tongan - lea fakatonga', code: 'to', category: "More" },
  { name: 'Turkish - Türkçe', code: 'tr', category: "More" },
  { name: 'Turkmen', code: 'tk', category: "More" },
  { name: 'Twi', code: 'tw', category: "More" },
  { name: 'Ukrainian - українська', code: 'uk', category: "More" },
  { name: 'Urdu - اردو', code: 'ur', category: "More" },
  { name: 'Uyghur', code: 'ug', category: "More" },
  { name: 'Uzbek - o‘zbek', code: 'uz', category: "More" },
  { name: 'Walloon - wa', code: 'wa', category: "More" },
  { name: 'Welsh - Cymraeg', code: 'cy', category: "More" },
  { name: 'Western Frisian', code: 'fy', category: "More" },
  { name: 'Xhosa', code: 'xh', category: "More" },
  { name: 'Yiddish', code: 'yi', category: "More" },
  { name: 'Yoruba - Èdè Yorùbá', code: 'yo', category: "More" },
  { name: 'Zulu - isiZulu', code: 'zu', category: "More" },
]

export const ageGroups = [
  { name: 'All ages', code: 'All ages' },
  { name: 'Infants (0-1 yr)', code: 'Infants' },
  { name: 'Toddlers (1-3 yr)', code: 'Toddlers' },
  { name: 'Preschool (3-4 yr)', code: 'Preschool' },
  { name: 'Young children (5-11 yr)', code: 'Young children' },
  { name: 'Adolescents (12-18 yr)', code: 'Adolescents' },
]
