export const languages = [
  { name: 'English', code: 'en' },
  { name: 'Spanish - español', code: 'es' },
  { name: 'Chinese (Cantonese)', code: 'zh-ca' },
  { name: 'Chinese (Mandarin)', code: 'zh-ma' },
  { name: 'Filipino (Tagalog)', code: 'fil' },
  { name: 'Vietnamese - Tiếng Việt', code: 'vi' },
  { name: 'Arabic - العربية', code: 'ar' },
  { name: 'French - français', code: 'fr' },
  { name: 'Hebrew - עברית', code: 'he' },
  { name: 'Korean - 한국어', code: 'ko' },
  { name: 'Russian - русский', code: 'ru' },
  { name: 'Portuguese (Brazil)', code: 'pt-BR' },
  { name: 'German - deutsch', code: 'de' },
  { name: 'Japanese - 日本語', code: 'ja' },
  { name: 'Hindi - हिन्दी', code: 'hi' },
  { name: 'Italian - italiano', code: 'it' },
  { name: 'Afrikaans', code: 'af' },
  { name: 'Albanian - shqip', code: 'sq' },
  { name: 'Amharic - አማርኛ', code: 'am' },
  { name: 'Aragonese - aragonés', code: 'an' },
  { name: 'Armenian - հայերեն', code: 'hy' },
  { name: 'Asturian - asturianu', code: 'ast' },
  { name: 'Azerbaijani - azərbaycan dili', code: 'az' },
  { name: 'Basque - euskara', code: 'eu' },
  { name: 'Belarusian - беларуская', code: 'be' },
  { name: 'Bengali - বাংলা', code: 'bn' },
  { name: 'Bosnian - bosanski', code: 'bs' },
  { name: 'Breton - brezhoneg', code: 'br' },
  { name: 'Bulgarian - български', code: 'bg' },
  { name: 'Catalan - català', code: 'ca' },
  { name: 'Central Kurdish - کوردی (دەستنوسی عەرەبی)', code: 'ckb' },
  { name: 'Corsican', code: 'co' },
  { name: 'Croatian - hrvatski', code: 'hr' },
  { name: 'Czech - čeština', code: 'cs' },
  { name: 'Danish - dansk', code: 'da' },
  { name: 'Dutch - Nederlands', code: 'nl' },
  { name: 'Esperanto - esperanto', code: 'eo' },
  { name: 'Estonian - eesti', code: 'et' },
  { name: 'Ewe', code: 'ewe' },
  { name: 'Faroese - føroyskt', code: 'fo' },
  { name: 'Finnish - suomi', code: 'fi' },
  { name: 'Galician - galego', code: 'gl' },
  { name: 'Ga', code: 'ga' },
  { name: 'Georgian - ქართული', code: 'ka' },
  { name: 'Greek - Ελληνικά', code: 'el' },
  { name: 'Guarani', code: 'gn' },
  { name: 'Gujarati - ગુજરાતી', code: 'gu' },
  { name: 'Hausa', code: 'ha' },
  { name: 'Hawaiian - ʻŌlelo Hawaiʻi', code: 'haw' },
  { name: 'Hungarian - magyar', code: 'hu' },
  { name: 'Icelandic - íslenska', code: 'is' },
  { name: 'Indonesian - Indonesia', code: 'id' },
  { name: 'Interlingua', code: 'ia' },
  { name: 'Irish - Gaeilge', code: 'ir' },
  { name: 'Kannada - ಕನ್ನಡ', code: 'kn' },
  { name: 'Kazakh - қазақ тілі', code: 'kk' },
  { name: 'Khmer - ខ្មែរ', code: 'km' },
  { name: 'Kurdish - Kurdî', code: 'ku' },
  { name: 'Kyrgyz - кыргызча', code: 'ky' },
  { name: 'Lao - ລາວ', code: 'lo' },
  { name: 'Latin', code: 'la' },
  { name: 'Latvian - latviešu', code: 'lv' },
  { name: 'Lingala - lingála', code: 'ln' },
  { name: 'Lithuanian - lietuvių', code: 'lt' },
  { name: 'Macedonian - македонски', code: 'mk' },
  { name: 'Malay - Bahasa Melayu', code: 'ms' },
  { name: 'Malayalam - മലയാളം', code: 'ml' },
  { name: 'Maltese - Malti', code: 'mt' },
  { name: 'Marathi - मराठी', code: 'mr' },
  { name: 'Mongolian - монгол', code: 'mn' },
  { name: 'Nepali - नेपाली', code: 'ne' },
  { name: 'Norwegian - norsk', code: 'no' },
  { name: 'Occitan', code: 'oc' },
  { name: 'Oriya - ଓଡ଼ିଆ', code: 'or' },
  { name: 'Oromo - Oromoo', code: 'om' },
  { name: 'Pashto - پښتو', code: 'ps' },
  { name: 'Persian - فارسی', code: 'fa' },
  { name: 'Polish - polski', code: 'pl' },
  { name: 'Portuguese (Portugal) - português (Portugal)', code: 'pt-PT' },
  { name: 'Punjabi - ਪੰਜਾਬੀ', code: 'pa' },
  { name: 'Quechua', code: 'qu' },
  { name: 'Romanian - română', code: 'ro' },
  { name: 'Romansh - rumantsch', code: 'rm' },
  { name: 'Scottish Gaelic', code: 'gd' },
  { name: 'Serbian - српски', code: 'sr' },
  { name: 'Serbo - Croatian', code: 'sh' },
  { name: 'Shona - chiShona', code: 'sn' },
  { name: 'Sindhi', code: 'sd' },
  { name: 'Sinhala - සිංහල', code: 'si' },
  { name: 'Slovak - slovenčina', code: 'sk' },
  { name: 'Slovenian - slovenščina', code: 'sl' },
  { name: 'Somali - Soomaali', code: 'so' },
  { name: 'Southern Sotho', code: 'st' },
  { name: 'Sundanese', code: 'su' },
  { name: 'Swahili - Kiswahili', code: 'sw' },
  { name: 'Swedish - svenska', code: 'sv' },
  { name: 'Tajik - тоҷикӣ', code: 'tg' },
  { name: 'Tamil - தமிழ்', code: 'ta' },
  { name: 'Tatar', code: 'tt' },
  { name: 'Telugu - తెలుగు', code: 'te' },
  { name: 'Thai - ไทย', code: 'th' },
  { name: 'Tigrinya - ትግርኛ', code: 'ti' },
  { name: 'Tongan - lea fakatonga', code: 'to' },
  { name: 'Turkish - Türkçe', code: 'tr' },
  { name: 'Turkmen', code: 'tk' },
  { name: 'Twi', code: 'tw' },
  { name: 'Ukrainian - українська', code: 'uk' },
  { name: 'Urdu - اردو', code: 'ur' },
  { name: 'Uyghur', code: 'ug' },
  { name: 'Uzbek - o‘zbek', code: 'uz' },
  { name: 'Walloon - wa', code: 'wa' },
  { name: 'Welsh - Cymraeg', code: 'cy' },
  { name: 'Western Frisian', code: 'fy' },
  { name: 'Xhosa', code: 'xh' },
  { name: 'Yiddish', code: 'yi' },
  { name: 'Yoruba - Èdè Yorùbá', code: 'yo' },
  { name: 'Zulu - isiZulu', code: 'zu' },
]

export const ageGroups = [
  { name: 'All ages', code: 'All ages' },
  { name: 'Infants (0-1 yr)', code: 'Infants' },
  { name: 'Toddlers (1-3 yr)', code: 'Toddlers' },
  { name: 'Preschool (3-4 yr)', code: 'Preschool' },
  { name: 'Young children (5-11 yr)', code: 'Young children' },
  { name: 'Adolescents (12-18 yr)', code: 'Adolescents' },
]
