import './styles/globals.scss'
import '@radix-ui/themes/styles.css'
import { Container, Theme } from '@radix-ui/themes'
import './themes-config.css'

import type { Metadata } from 'next'
import { DMSans } from './fonts'

export const metadata: Metadata = {
  title: 'StoryKasa Beta',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={DMSans.variable}>
        <Theme accentColor="gold" grayColor="sand">
          <Container size="4" p="5">
            {children}
          </Container>
        </Theme>
      </body>
    </html>
  )
}
