import { DM_Sans } from 'next/font/google'
import './styles/globals.scss'
import '@radix-ui/themes/styles.css'
import {
  Box,
  Container,
  Flex,
  Grid,
  Link,
  Theme,
  ThemePanel,
} from '@radix-ui/themes'
import './themes-config.css'
import Image from 'next/image'

import type { Metadata } from 'next'

const DMSans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm-sans',
})

export const metadata: Metadata = {
  title: 'StoryKasa Beta',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={DMSans.variable}>
        <Theme accentColor="gold" grayColor="sand">
          <Container size="4" p="5">
            {children}
          </Container>
        </Theme>
      </body>
    </html>
  )
}
